POST http://localhost:3000/v1/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6InNhaWQuYWJyYWhhbS5tLmdAZ21haWwuY29tIiwiaWF0IjoxNzM4NjE3NzU3LCJleHAiOjE3Mzg2MjEzNTcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Tm2Imj3a30hrQI-c4RIFoAT_CCrflwcq68SU76zHJ6o

{
    "title": "What's new with NestJs",
    "postType": "post",
    "slug": "created-by-user-gugul",
    "status": "draft",
    "content": "test content",
    "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
    "featuredImageUrl": "http://localhost.com/images/image1.jpg",
    "publishOn": "2024-03-16T07:46:32Z",
    //"tags": ["nestjs", "typescript"],
    "metaOptions": {
           "metaValue": "{ \"sidebarEnabled\": true, \"footerActive\": true }"
    },
    "tags": [1]
}