## POST Request For Users controller
POST http://localhost:3000/v1/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "jhon@doe.com",
    "password": "Password123@"
}