POST http://localhost:3000/v1/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoia2FpQGRvZS5jb20iLCJpYXQiOjE3Mzg1OTA2MjgsImV4cCI6MTczODU5NDIyOCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.wArq_ZSIWGJUrOynUiOvihc3inW8jy8HDESnxGBRLcg
{
     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczODU5MDYyOCwiZXhwIjoxNzM4NTk0MjI4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.S1UnfEM_lAIGPhUwjeHxIeT624kOKQidufNZFe1gtr8"
}