const {
  NODE_ENV: environment = 'development',
  PORT: port = 3000,
  HOST_API: hostApi = 'http://localhost:3000/api',
  LOGGER_LEVEL: loggerLevel = 'log',
  CLD_CLOUD_NAME: cloudName,
  CLD_API_KEY: apiKey,
  CLD_API_SECRET: apiSecret,
  API_VERSION: apiVersion,
  AWS_PUBLIC_BUCKET_NAME: awsBucketName,
  AWS_REGION: awsRegion,
  AWS_CLOUDFRONT_URL: awsCloudfrontURL,
  AWS_ACCESS_KEY_ID: awsAccessKeyId,
  AWS_SECRET_ACCESS_KEY: awsSecretAccessKey,
  MAIL_HOST: mailHost,
  SMTP_USERNAME: smptUsername,
  SMTP_PASSWORD: smptPassword,
} = process.env;

export const AppConfiguration = () => ({
  environment,
  port,
  hostApi,
  loggerLevel,
  cloudName,
  apiKey,
  apiSecret,
  apiVersion,
  awsBucketName,
  awsRegion,
  awsCloudfrontURL,
  awsAccessKeyId,
  awsSecretAccessKey,
  mailHost,
  smptUsername,
  smptPassword,
});
